FROM        python:3.8-slim
ENV         LANG C.UTF-8

RUN         apt -y update &&\
            apt -y dist-upgrade

WORKDIR     /tmp
RUN         pip install poetry

COPY        pyproject.toml /tmp/
COPY        poetry.lock /tmp/
RUN         poetry export -f requirements.txt > requirements.txt
RUN         pip install -r requirements.txt

RUN         apt -y install git
RUN         pip install awscli awsebcli
