FROM    python:3.7.3-slim
ENV     LANG C.UTF-8
RUN     apt -y update &&\
        apt -y dist-upgrade &&\
        apt -y install nginx && \
        apt -y autoremove

COPY    .requirements /tmp/requirements
RUN     pip3 install -r /tmp/requirements/production.txt

COPY    deploy.py /tmp
COPY    .projects_requirements /tmp/projects_requirements
RUN     python3 /tmp/deploy.py --venv
